services:
  gitlab:
    image: gitlab/gitlab-ce:18.4.3-ce.0
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.mc.localhost'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false  # Nginx reverse proxy handles HTTPS
    volumes:
      - ./core/gitlab/config:/etc/gitlab
      - ./core/gitlab/logs:/var/log/gitlab
      - ./core/gitlab/data:/var/opt/gitlab
    networks:
      - internal

  # backrest:
  #   image: garethgeorge/backrest:v1.10.1-scratch
  #   restart: unless-stopped
  #   volumes:
  #     - ./backups:/backups
  #     - ./gitlab/data:/source/gitlab:ro
  #     - ./portus:/source/portus:ro
  #   networks:
  #     - internal

networks:
  internal:
    name: mastercompose_internal
    external: true
