services:
  nginx-proxy:
    image: nginx:mainline-alpine-perl
    container_name: mastercompose-nginx-proxy
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ${NGINX_DATA}:/data
      - ${NGINX_LETSENCRYPT}:/etc/letsencrypt
      - ${NGINX_CUSTOM}:/etc/nginx/templates
      - ${NGINX_HTML}:/etc/nginx/html
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - zerotier

  zerotier:
    image: zerotier/zerotier:1.14.2
    container_name: mastercompose-zerotier
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      ZT_NETWORK: ${ZT_NETWORK}
    volumes:
      - ${ZEROTIER_DATA}:/var/lib/zerotier-one
    network_mode: "host"
    # command: >
    #   sh -c '
    #     mkdir -p /var/lib/zerotier-one &&
    #     echo -n "{ \"settings\": { \"primaryPort\": ${ZT_PORT:-30120} } }" > /var/lib/zerotier-one/local.conf &&
    #     echo "ZeroTier port set to ${ZT_PORT:-30120}" &&
    #     exec /usr/sbin/zerotier-one -d -p ${ZT_PORT:-30120}
    #   '

networks:
  internal:
    name: mastercompose_internal
    driver: bridge
