services:

  nginx:
    image: nginx:mainline-alpine-perl
    container_name: mastercompose-nginx
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ${NGINX_DATA}:/data
      - ${NGINX_LETSENCRYPT}:/etc/letsencrypt
      - ${NGINX_CUSTOM}:/etc/nginx/templates
      - ${NGINX_HTML}:/usr/share/nginx/html
      - ${NGINX_SSL}:/etc/nginx/ssl

    ports:
      - "80:80"
      - "443:443"

    networks:
      proxy:
      internal:
        ipv4_address: ${NGINX_IP}


  zerotier:
    image: zerotier/zerotier:1.14.2
    container_name: mastercompose-zerotier
    restart: unless-stopped

    env_file:
      - .env

    userns_mode: "host"

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun

    environment:
      ZT_NETWORK: ${ZT_NETWORK}

    volumes:
      - ${ZEROTIER_DATA}:/var/lib/zerotier-one

    network_mode: host


  portainer:
    image: portainer/portainer-ce:latest
    container_name: mastercompose-portainer
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data

    ports:
      - "${PORTAINER_PORT}:${PORTAINER_PORT}"
    networks:
      internal:
          ipv4_address: ${PORTAINER_ID}


networks:

  proxy:
    name: mastercompose_proxy
    driver: bridge

  internal:
    name: mastercompose_internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16