services:

#* Forgero
    forgejo:
        image: codeberg.org/forgejo/forgejo:13
        container_name: mastercompose-forgejo
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - USER_UID=1000
            - USER_GID=1000

            # Database
            - FORGEJO__database__DB_TYPE=postgres
            - FORGEJO__database__HOST=${FORGEJO_DB_HOST}
            - FORGEJO__database__NAME=${FORGEJO_DB_NAME}
            - FORGEJO__database__USER=${FORGEJO_DB_USER}
            - FORGEJO__database__PASSWD=${FORGEJO_DB_PASS}

            # Server
            - FORGEJO__server__DOMAIN=${FORGEJO_SERVER_DOMAIN}
            - FORGEJO__server__ROOT_URL=${FORGEJO_SERVER_ROOT_URL}
            - FORGEJO__server__HTTP_PORT=${FORGEJO_HTTP_PORT}
            - FORGEJO__server__SSH_DOMAIN=${FORGEJO_SERVER_DOMAIN}
            - FORGEJO__server__START_SSH_SERVER=true
            - FORGEJO__server__SSH_PORT=2222
            - FORGEJO__server__SSH_LISTEN_PORT=2222

            # Security and registration
            - FORGEJO__service__DISABLE_REGISTRATION=true

            # MAIL
            - FORGEJO__mailer__ENABLED=true
            - FORGEJO__mailer__FROM=Forgejo<noreply@paulosergio.pierdona.nom.br>
            - FORGEJO__mailer__USER=${FORGEJO_MAILER_USER}
            - FORGEJO__mailer__PASS=${FORGEJO_MAILER_PASS}
            - FORGEJO__mailer__PROTOCOL=smtps
            - FORGEJO__mailer__SMTP_ADDR=smtp.gmail.com
            - FORGEJO__mailer__SMTP_PORT=465

            - FORGEJO__service__ENABLE_NOTIFY_MAIL=${FORGEJO_SERVICE_ENABLE_NOTIFY_MAIL}
            - FORGEJO__service__REGISTER_EMAIL_CONFIRM=${FORGEJO_SERVICE_REGISTER_EMAIL_CONFIRM}

            # Optional: Auto-create admin user
            - FORGEJO__security__INSTALL_LOCK=true
            - FORGEJO__security__SECRET_KEY=$(openssl rand -hex 32)

            # Others
            - FORGEJO__service__REQUIRE_SIGNIN_VIEW=false
        ports:
            - "${FORGEJO_SSH_PORT}:2222" # SSH access
        volumes:
            - ./core/forgejo/data:/data
        networks:
            - internal
            - forgejo
        depends_on:
            - forgejo_db

    forgejo_db:
        image: postgres:14
        container_name: mastercompose-forgejo_db
        restart: always
        environment:
            - POSTGRES_USER=${FORGEJO_DB_USER}
            - POSTGRES_PASSWORD=${FORGEJO_DB_PASS}
            - POSTGRES_DB=${FORGEJO_DB_NAME}
        networks:
            - forgejo
        volumes:
            - ./core/forgejo/postgres:/var/lib/postgresql/data

    # Optional backup service
    backrest:
        image: garethgeorge/backrest:v1.10.1
        container_name: mastercompose-backrest
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./core/backrest/config:/config
            - ./core/backups:/backups
        networks:
            - internal

networks:
    internal:
        name: mastercompose_internal
        external: true
    forgejo:
        name: mastercompose_forgejo
        external: false