services:
  nginx-proxy:
    image: nginx:mainline-alpine-perl
    container_name: mastercompose-nginx-proxy
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ${NGINX_DATA}:/data
      - ${NGINX_LETSENCRYPT}:/etc/letsencrypt
      - ${NGINX_CUSTOM}:/etc/nginx/conf.d

  zerotier:
    image: zerotier/zerotier:1.14.2
    container_name: mastercompose-zerotier
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      ZT_NETWORK: ${ZT_NETWORK}
    ports:
      - "${ZT_PORT}:9993"
    volumes:
      - ${ZEROTIER_DATA}:/var/lib/zerotier-one
